# Dockerfile for goldapps production
FROM golang:1.23-alpine AS buildStage

# Install git
RUN apk update
RUN apk upgrade
RUN apk add --update git

# Copy sources
RUN mkdir -p /goldapps
COPY . /goldapps
WORKDIR /goldapps/goldapps/web

# Grab dependencies
RUN go get -d -v ./...

# build binary
RUN go install -v
RUN mkdir /app
RUN mv $GOPATH/bin/web /app/goldapps

##########################
#    PRODUCTION STAGE    #
##########################
FROM alpine

# Set user
RUN addgroup -S app
RUN adduser -S -G app -s /bin/bash app
USER app:app

# Copy execution script
COPY ./sleep_and_run.sh /app/sleep_and_run.sh

# Copy binary
COPY --from=buildStage /app/goldapps /app/goldapps

ENV WAIT 15s

# Set good defaults
WORKDIR /app
ENTRYPOINT ./goldapps
