version: "2"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: goldapps:stable
    restart: always
    entrypoint: ./sleep_and_run.sh
    command: ["-from ldap", "-to gapps", "-y", "-dry"]
    volumes:
      - ./cmd/config.toml:/app/config.toml:ro
      - ./cmd/gapps.json:/app/gapps.json:ro
    environment:
      - WAIT=2d