version: "2"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: goldapps:stable
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./gapps.json:/app/gapps.json:ro
      - ./additions.json:/app/additions.json:ro
      - ./gamma.json:/app/gamma.json:ro
    networks:
      - gamma

  web:
    build:
      dockerfile: Dockerfile.web
      context: .
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./gapps.json:/app/gapps.json:ro
      - ./additions.json:/app/additions.json:ro
      - ./gamma.json:/app/gamma.json:ro
    environment:
      GIN_MODE: debug
      SESSION_SECRET: secret
      COOKIE_DOMAIN: localhost
      GAMMA_URL: http://localhost:8081
      REDIRECT_GAMMA_URL: http://localhost:8081
      # Gamma client info
      GAMMA_CLIENT_ID: id
      GAMMA_CLIENT_SECRET: key
      GAMMA_REDIRECT_URL: http://localhost:8080/api/authenticate
    networks:
      - gamma
    ports:
      - 8080:8080

networks:
  gamma:
    external: True