version: "2"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: goldapps:stable
    restart: always
    entrypoint: ./sleep_and_run.sh
    command: [
      "-from ldap",
      "-to gapps",
      "-additions additions.json",
      "-y",
      "-dry"
    ]
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./gapps.json:/app/gapps.json:ro
      - ./additions.json:/app/additions.json:ro
    environment:
      - WAIT=1h