version: "2"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: goldapps:stable
    network_mode: host # Easier since gamma is running with a different docker-compose
    command: [
      "-from ldap",
      "-to gapps",
      "-additions additions.json",
      "-y",
      "-dry"
    ]
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./gapps.json:/app/gapps.json:ro
      - ./additions.json:/app/additions.json:ro

  web:
    build:
      dockerfile: Dockerfile.web
      context: .
    network_mode: host # Easier since gamma is running with a different docker-compose
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./gapps.json:/app/gapps.json:ro
      - ./additions.json:/app/additions.json:ro
    environment:
      GIN_MODE: debug
      SESSION_SECRET: secret
      AUTH_SECRET: secret
      CLIENT_ID: id
      GAMMA_URL: http://localhost:8081
      REDIRECT_GAMMA_URL: http://localhost:8081
      CALLBACK_URL: http://localhost:3001/callback
      COOKIE_DOMAIN: localhost
