[gapps.consumer]
    servicekeyfile = "gapps1.json"
    adminaccount = "admin@example1.ex"

[gapps.provider]
    servicekeyfile = "gapps2.json"
    adminaccount = "admin@example2.ex"

[ldap]
	url = "ldap.example.ex:999"
	servername = "example.ex"
	user = "cn=god,dc=example,dc=ex"
	password = "secret"
	custom = ["my_custom_filter"]

[ldap.groups]
	basedn = "ou=some,ou=groups,dc=example,dc=ex"
	filter = "(&(objectClass=Group))"
	attibutes = ["cn", "displayName", "mail", "member"]

[ldap.users]
	basedn = "ou=people,dc=example,dc=ex"
	filter = "(&(objectClass=Group))"
	attibutes = ["uid", "mail"]

[ldap.my_custom_filter]
    mail = "custom@example.ex"
    basedn = "ou=groups,dc=chalmers,dc=it"
    filter = "(&(objectClass=Group))"
    parent_filter = "(&(ou=%childRDN%))"
    attibutes = ["cn", "displayName", "mail"]
